# HTML
# Archive your static HTML project and save it with the build record.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

<!DOCTYPE html>
<html>

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        body{
            font-family: Arial, Helvetica, sans-serif;
        }

        /* Full-width input fields */

        input[type=text],
        input[type=password] {
            width: 100%;
            padding: 12px 20px;
            margin: 8px 0;
            display: inline-block;
            border: 1px solid #ccc;
            box-sizing: border-box;
        }

        /* Set a style for all buttons */

        button {
            background-color: #0415aa;
            color: rgb(226, 181, 181);
            padding: 10px 18px;
            margin: 8px 0;
            border: none;
            cursor: pointer;
            width: auto;
        }

        button:hover {
            opacity: 0.8;
        }

        .signupbtn {
            width: auto;
            padding: 10px 18px;
            background-color: white;
        }

        /* Extra styles for the cancel button */

        .cancelbtn {
            width: auto;
            padding: 10px 18px;
            background-color: lavender;
        }

        /* Center the image and position the close button */

        .imgcontainer {
            text-align: center;
            margin: 10px 0 10px 0;
            position: relative;
        }

        img.avatar {
            width: 40%;
            border-radius: 50%;
        }

        .container {
            padding: 16px;
        }

        span.psw {
            float: right;
            padding-top: 16px;
        }

        /* The Modal (background) */

        .modal {
            display: none;
            /* Hidden by default */
            position: fixed;
            /* Stay in place */
            z-index: 1;
            /* Sit on top */
            left: 0;
            top: 0;
            width: 100%;
            /* Full width */
            height: 100%;
            /* Full height */
            overflow: auto;
            /* Enable scroll if needed */
            background-color: lavender;
            /* Fallback color */
            background-color: lavender;
            /* Black w/ opacity */
            padding-top: 60px;
        }

        /* Modal Content/Box */

        .modal-content {
            background-color: lavender;
            margin: 5% auto 15% auto;
            /* 5% from the top, 15% from the bottom and centered */
            border: 1px solid #888;
            width: 80%;
            /* Could be more or less, depending on screen size */
        }

        /* The Close Button (x) */

        .close {
            position: absolute;
            right: 25px;
            top: 0;
            color: lavender;
            font-size: 35px;
            font-weight: bold;
        }

        .close:hover,
        .close:focus {
            color: red;
            cursor: pointer;
        }

        /* Add Zoom Animation */

        .animate {
            -webkit-animation: animatezoom 0.6s;
            animation: animatezoom 0.6s
        }

        @-webkit-keyframes animatezoom {
            from {
                -webkit-transform: scale(0)
            }
            to {
                -webkit-transform: scale(1)
            }
        }

        @keyframes animatezoom {
            from {
                transform: scale(0)
            }
            to {
                transform: scale(1)
            }
        }

        /* Change styles for span and cancel button on extra small screens */

        @media screen and (max-width: 300px) {
            span.psw {
                display: block;
                float: none;
            }
            .signupbtn {
                width: 100%;
                float: right;
            }

            .cancelbtn {
                width: 100%;
                float: right;
            }
            .modal1 {
                display: none;
                /* Hidden by default */
                position: fixed;
                /* Stay in place */
                z-index: 1;
                /* Sit on top */
                left: 0;
                top: 0;
                width: 100%;
                /* Full width */
                height: 100%;
                /* Full height */
                overflow: auto;
                /* Enable scroll if needed */
                background-color: lavender;
                padding-top: 50px;
            }

            /* Modal Content/Box */
            .modal1-content {
                background-color: lavender;
                margin: 5% auto 15% auto;
                /* 5% from the top, 15% from the bottom and centered */
                border: 1px solid #888;
                width: 80%;
                /* Could be more or less, depending on screen size */
            }

            /* Style the horizontal ruler */
            hr {
                border: 1px solid #150f0f;
                margin-bottom: 25px;
            }
        }
    </style>
</head>

<body background-color= lavender>

    <center>
        <h2> ONLINE LOAN APPLICATION </h2>
    </center>

    <center><button onclick="document.getElementById('id01').style.display='block'" style="width:auto;">Login</button></center>

    <div id="id01" class="modal">

        <form class="modal-content animate" action="/action_page.php" method="post">
            <div class="imgcontainer">
                <span onclick="document.getElementById('id01').style.display='none'" class="close" title="Close Modal">&times;</span>

            </div>

            <div class="container">
                <h1>Login</h1>
                <p>Please login to your account</p>
                <label for="uname"><b>Username</b></label>
                <input type="text" placeholder="Enter Username" name="uname" required>

                <label for="psw"><b>Password</b></label>
                <input type="password" placeholder="Enter Password" name="psw" required>
                <button type="submit">SUBMIT</button>   
                <input type="checkbox" checked="checked"> Remember me   
                <button type="button" class="cancelbtn"> Cancel</button>   
                Forgot <a href="#"> password? </a>   
            </div>   
        </form>     
    </body>     
    </html>